export const FETCH_RANDOM_QUOTE = "FETCH_RANDOM_QUOTE";
export const FETCH_RANDOM_QUOTE_COLOR = "FETCH_RANDOM_QUOTE_COLOR";
export const SEARCH_WIKIPEDIA = "SEARCH_WIKIPEDIA";
export const FETCH_MAP_DATA = "FETCH_MAP_DATA";
export const FETCH_WEATHER = "FETCH_WEATHER_DATA";